# Generated by Django 2.0.7 on 2018-07-15 22:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_DNA', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('precision', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
        ),
        migrations.CreateModel(
            name='OptimumDNA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNA_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='individual',
            name='optimum_DNA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genetic.OptimumDNA'),
        ),
    ]
